android.defaults.buildfeatures.resvalues=false
android.dependency.useConstraints=true
android.enableAppCompileTimeRClass=true
android.r8.optimizedResourceShrinking=true
android.r8.strictFullModeForKeepRules=false
android.sdk.defaultTargetSdkToCompileSdkIfUnset=true
android.uniquePackageNames=false
android.useAndroidX=true
android.enableJetifier=false
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.usesSdkInManifest.disallowed=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false